### ISSUE TITLE
write script to automate updating dependencies

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/chart-logging#9]
[this](https://github.com/samsung-cnct/k2-charts/issues/120#issuecomment-337403234) comment explains the process of vendoring dependencies and then adjust file locations - this should be automated.

**Comment by coffeepac** [comment]
@joejulian  to provide smooth general method for this

**Comment by joejulian** [comment]
Should work like:
```
# registry plugin dependencies
appr:
- name: quay.io/ant31/ghost
  repository: appr://
  version: '>=0.4.5'   # can use version queries

- name: quay.io/ant31/otherapp
  repository: appr://
  version: ':beta'   # can use channels ( :chan_name) 

# Upstream dependencies management:
dependencies:
- name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 0.6.0
```
